// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVPn2wwDCXPO-vLUoFr2ZPtJcRCw4h7E4',
    appId: '1:495270461047:web:3af43b01b22b8fc03d5072',
    messagingSenderId: '495270461047',
    projectId: 'fruit-hub-5d041',
    authDomain: 'fruit-hub-5d041.firebaseapp.com',
    storageBucket: 'fruit-hub-5d041.firebasestorage.app',
    measurementId: 'G-WVD0YV0V46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBASSwj7heEoLK2bJOazkNTdHEeSSY8g1M',
    appId: '1:495270461047:android:5a80c9620a1ae1a43d5072',
    messagingSenderId: '495270461047',
    projectId: 'fruit-hub-5d041',
    storageBucket: 'fruit-hub-5d041.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKCGBbwQuWwu4dX7KYCpu9lWtXC2aAJK0',
    appId: '1:495270461047:ios:ae53c490cd0b90193d5072',
    messagingSenderId: '495270461047',
    projectId: 'fruit-hub-5d041',
    storageBucket: 'fruit-hub-5d041.firebasestorage.app',
    androidClientId: '495270461047-c3v85vbdjl292clt4dabvu7tsrft8r6n.apps.googleusercontent.com',
    iosClientId: '495270461047-vggi9ipmgg170t5l1or9luecbg12gumb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKCGBbwQuWwu4dX7KYCpu9lWtXC2aAJK0',
    appId: '1:495270461047:ios:ae53c490cd0b90193d5072',
    messagingSenderId: '495270461047',
    projectId: 'fruit-hub-5d041',
    storageBucket: 'fruit-hub-5d041.firebasestorage.app',
    androidClientId: '495270461047-c3v85vbdjl292clt4dabvu7tsrft8r6n.apps.googleusercontent.com',
    iosClientId: '495270461047-vggi9ipmgg170t5l1or9luecbg12gumb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVPn2wwDCXPO-vLUoFr2ZPtJcRCw4h7E4',
    appId: '1:495270461047:web:e4e77ae00bae18213d5072',
    messagingSenderId: '495270461047',
    projectId: 'fruit-hub-5d041',
    authDomain: 'fruit-hub-5d041.firebaseapp.com',
    storageBucket: 'fruit-hub-5d041.firebasestorage.app',
    measurementId: 'G-R2SPVGEXT8',
  );
}
